
/** ----------------------------------------------------------------------------------------------------
* 
*	This code was automatically generated by the LeanFT Application Model code generator.
*
*	Changes to this file may cause incorrect behavior and will be lost 
*	when the code is regenerated.
*
*   ----------------------------------------------------------------------------------------------------
*/
package model;

import javax.annotation.Generated;

import com.hp.lft.sdk.*;
import com.hp.lft.sdk.internal.*;

@Generated(value = { "This class is automatically generated by the LeanFT Application Model code generator - version \"14.02\"" })
public class Terminal extends AppModelBase {	
	public Terminal(TestObject contextTestObject) throws GeneralLeanFtException
	{
		setName("Terminal");
				rebuildDescriptions();
	}	
}
